config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#top'
  get 'home/about'
  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :timeline
      get :quit
      get :favorite
    end
    member do
      get :following, :followers
    end
    resources :relationships, only: [:create, :destroy]
  end

  resources :places, only: [:index, :new, :create, :show] do
    collection do
      get :confirm
    end
    resources :reviews, only: [:new, :create, :destroy, :show] do
      # collection do
      #   get :confirm
      # end
      resource :favorites, only: [:create, :destroy]
      resources :review_comments, only: [:create, :destroy]
    end
  end
  get 'favorites/index'
end

app/models/review_comment.rb
class ReviewComment < ApplicationRecord
  belongs_to :review
  belongs_to :user

  validates :comment, presence: true,
                      length: { maximum: 128 }
end

app/controllers/review_comments_controller.rb
class ReviewCommentsController < ApplicationController
  def create
    @place = Place.find(params[:place_id])
    @review = Review.find(params[:review_id])
    comment = current_user.review_comments.new(review_comment_params)
    comment.review_id = @review.id
    if comment.save
      render :index
    else
      @review_comment = ReviewComment.new
      @review_comments = @review.review_comments.reverse_order
      render template: "reviews/show"
    end
  end

  def destroy
    @place = Place.find(params[:place_id])
    @review = Review.find(params[:review_id])
    comment = current_user.review_comments.find_by(id: params[:id])
    comment.destroy
    redirect_to place_review_path(place_id: @place, id: @review)
  end

  private

  def review_comment_params
    params.require(:review_comment).permit(:comment)
  end
end

app/helpers/review_comment_helper.rb
module ReviewCommentHelper
end

app/views/review_comments/_count.html.erb
<div class="reviews__comment">
	<%= review.review_comments.count %>件コメント
</div>

app/views/review_comments/_form.html.erb
<div class="review__comment">
	<%= form_with(model: [place, review, review_comment], remote: true) do |f| %>
		<div class="row">
			<div class="col-sm-10">
				<div class="form-group">
					<p>コメントを投稿</p>
					<%= f.text_area :comment, rows:3, :placeholder=> "128文字以内", class: "form-control" %>
				</div>
			</div>
			<div class="col-sm-1 align-self-end">
				<div class="form-group">
					<%= f.submit "送信する", class: "btn btn-info" %>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/review_comments/_index.html.erb
<div class="review__comments">
	<% review_comments.each do |review_comment| %>
	<div class="review__comment-user">
		<div class="review__cooment-usere-img col-sm-1">
			<%= attachment_image_tag review_comment.user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "no_image.jpg" %>
		</div>
		<div class="offset-sm-2">
			<div class="review__comment-user-name">
				<%= link_to user_path(review_comment.user) do %>
					<b><%= review_comment.user.nickname %></b>
				<% end %>
			</div>
			<% if current_user == review_comment.user %>
				<div class="review__comment-delete">
					<%= link_to "削除する", place_review_review_comment_path(place_id: @place.id, review_id: @review.id, id: review_comment.id),
					method: :delete, remote: true, "data-confirm"=> "本当に削除しますか？？", class: "btn btn-danger btn-small" %>
				</div>
			<% end %>
			<div class="review__comment-user-info">
				<%= review_comment.created_at.strftime('%Y/%m/%d/ %H:%M') %>
			</div>
		</div>
	</div>
	<div class="review__comment-list">
		<div class="offset-sm-2">
			<%= simple_format(review_comment.comment) %>
		</div>
	</div>
	<% end %>
</div>

app/views/review_comments/index.js.erb
$("#comment_area").html("<%= j(render 'index', review_comments: @review.review_comments ) %>")
$("textarea").val('')
$('#comment_count').html("<%= j(render 'count', review: @review) %>")