config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#top'
  get 'home/about'
  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :timeline
      get :quit
      get :favorite
    end
    member do
      get :following, :followers
    end
    resources :relationships, only: [:create, :destroy]
  end

  resources :places, only: [:index, :new, :create, :show] do
    collection do
      get :confirm
    end
    resources :reviews, only: [:new, :create, :destroy, :show] do
      # collection do
      #   get :confirm
      # end
      resource :favorites, only: [:create, :destroy]
      resources :review_comments, only: [:create, :destroy]
    end
  end
  get 'favorites/index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  attachment :profile_image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :active_relationships,  class_name: "Relationship",
                                   foreign_key: "follower_id",
                                   dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :review_comments, dependent: :destroy

  enum gender: { 男性: 1, 女性: 2 }
  enum address: {
    北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7, 茨城県: 8, 栃木県: 9, 群馬県: 10,
    埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14, 新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
    岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24, 滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35, 徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39, 福岡県: 40,
    佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46, 沖縄県: 47,
  }

  validates :nickname, presence: true,
                       length: { maximum: 10 }
  validates :gender,   presence: true
  validates :birthday, presence: true
  validates :address,  presence: true

  # 　ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # ユーザーの生年月日から年代表示
  def age_decade
    age = (Date.today.strftime("%Y%m%d").to_i - birthday.strftime("%Y%m%d").to_i) / 10000
    "#{age.to_s.chop}0代"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :baria_user, only: :edit

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    reset_session
    flash[:notice] = "ご利用ありがとうございました。退会しました。"
    redirect_to root_path
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  def timeline
    @user = current_user
    @users = @user.following
    @reviews_all = Review.all.reverse_order
    @reviews = []
    # # if singned_in?
    # # end
    @reviews_all.each do |review|
      # 自分の投稿を表示
      if review.user_id == current_user.id
        @reviews.push(review)
      end
      # フォローしている人の投稿を表示
      @users.each do |user|
        if review.user_id == user.id
          @reviews.push(review)
        end
      end
    end
  end

  def favorite
    @user = User.find(params[:id])
    @favorites = @user.favorites
  end

  def quit
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :gender, :birthday, :address, :profile_image)
  end

  def baria_user
    @user = User.find(params[:id])
    if current_user != @user
      flash[:alert] = "不正なアクセスです"
      redirect_to root_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html 2.erb
<div class="profile-follow">
		<% if current_user.following?(user) %>
			<%= link_to "フォロー解除", user_relationship_path(user.id), method: :delete, class: "btn btn-danger btn-block"  %>
		<% else %>
			<%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-primary btn-block" %>
	<% end %>
</div>

app/views/users/_follow.html.erb
<div class="profile-follow">
		<% if current_user.following?(user) %>
			<%= link_to "フォロー解除", user_relationship_path(user.id), method: :delete, class: "btn btn-danger btn-block"  %>
		<% else %>
			<%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-primary btn-block" %>
	<% end %>
</div>

app/views/users/_profile.html 2.erb
<div class="col-sm-3 profile">
	<div class="position-fixed">
		<h2>Profile</h2>

		<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: "no_image.jpg" %>

		<table class="profile__list">
				<tr>
					<th><%= user.nickname %></th>
					<td></td>
				</tr>
				<tr>
					<th>フォロー</th>
					<td><%= link_to user.following.count, following_user_path(user) %></td>
				</tr>
				<tr>
					<th>フォロワー</th>
					<td><%= link_to user.followers.count, followers_user_path(user) %></td>
				</tr>
		</table>
		<% if current_user == user %>
			<div class="profile__btn">
				<%= link_to "プロフィール編集", edit_user_path(current_user.id),class: "btn btn-green btn-block" %>
			</div>
		<% else %>
			<div class="profile__btn">
				<%= render 'users/follow', user: user%>
			</div>
		<% end %>
		<div class="profile__btn">
			<%= link_to "いいねリスト", favorite_user_path(user), class: "btn btn-orange btn-block" %>
		</div>
		<div class="profile__btn">
			<%= link_to "レビューを投稿する", new_place_path, class: "btn btn-yellow btn-block" %>
		</div>
	</div>
</div>

app/views/users/_user_list.html 2.erb
<table class="follow__list">
	<thead>
		<tr>
			<th>プロフィール写真</th>
			<th>ニックネーム</th>
			<th>年代</th>
			<th>投稿数</th>
			<th></th>
		</tr>
	</thead>
	<% users.each do |user| %>
	<tbody>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, :fill, 65, 65, format: "jpeg", fallback: "no_image.jpg" %></td>
			<td><%= link_to user_path(user) do %>
				<%= user.nickname%>
				<% end %></td>
			<td><%= user.age_decade %></td>
			<td><%= user.reviews.count %></td>


			<td><% unless current_user == user %>
					<%= render 'follow',user: user %>
				<% end %>
			</td>
		</tr>
	</tbody>
	<% end %>
</table>

app/views/users/edit.html.erb
<%= render 'layouts/error_messages', model: @user %>
<h2>プロフィール編集</h2>

<%= form_for @user do |f| %>
<div class="form">

   <div class="form-group row">
    	<div class="col-sm-2">
    		<p>プロフィール画像</p>
    	</div>
    	<div class="col-sm-4">
    		<!-- 画像プレビュー -->
    		<%= f.label :profile_image do %>
    			<%= attachment_image_tag @user, :profile_image, id: "preview", size: '100x100',  fallback: "no_image.jpg" %>
    		<% end %>
    		<%= f.attachment_field :profile_image, id: :profile_img %>
    	</div>
    </div>

    <div class="form-group row">
      <div class="col-sm-2">
        <%= f.label :nickname, "ニックネーム", class: "col-form-label" %>
      </div>
      <div class="col-sm-5">
        <%= f.text_field :nickname, :placeholder=>"例）ココイキ", autofocus: true, class: "form-control" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-2">
        <label>性別</label>
      </div>
      <div class="form-check">
        <%= f.radio_button :gender, "男性" %>
        <%= f.label :gender, "男性", value:"男性", class: "form-check-label" %>
      </div>
      <div class="form-check">
        <%= f.radio_button :gender, "女性" %>
        <%= f.label :gender, "女性", value:"女性", class: "form-check-label" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-2">
        <%= f.label :birthday, "生年月日", class: "col-form-label" %>
      </div>
      <div class="col-sm-3">
        <%= f.date_select :birthday, {use_month_numbers: true, start_year:1930, end_year:(Time.now.year-10), default: Date.new(1990, 1, 1),date_separator: ' / '}, {class: "form-control bootstrap-date-only-width"} %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-2">
        <%= f.label :address, "お住まい" %>
      </div>
      <div class="col-sm-2">
        <%= f.select :address, User.addresses.keys,{prompt: "選択してくだい"},class: "custom-select" %>
      </div>
    </div>

	<div class="form-group row">
		<div class="offset-sm-2">
	      <%= f.submit "保存する", class: "btn btn-success" %>
	    </div>
	    <!-- 退会ページリンク -->
	    <div class="offset-sm-5">
		<%= link_to "退会する", quit_user_path(@user), class: "btn btn-sm btn-danger" %>
		</div>
	</div>
</div>
<% end %>

app/views/users/favorite.html 2.erb
<div class="row">
	<%= render 'profile', user: @user %>
	<div class="col-sm-9">

		<h1>いいね一覧</h1>
		<% if @favorites.count > 0 %>
			<% @favorites.each do |favorite| %>
				<%= render 'reviews/post_content', user: favorite.review.user, review: favorite.review %>
			<% end %>
		<% else %>
			<h3 class="review__none">いいねがありません</h3>
		<% end %>
	</div>
</div>

app/views/users/followers.html.erb
<div class="row">
	<%= render 'profile', user: @user %>
	<div class="col-sm-9">
		<h2>フォロワーリスト</h2>
		<% if @users.count > 0 %>
			<%= render 'user_list', user: @user ,users: @users %>
		<% else %>
			<p>ユーザーがいません。</p>
		<% end %>
	</div>
</div>

app/views/users/following.html 2.erb
<div class="row">
	<%= render 'profile', user: @user %>
	<div class="col-sm-9">
		<h2>フォローリスト</h2>
		<% if @users.count > 0 %>
			<%= render 'user_list', user: @user, users: @users %>
		<% else %>
			<p>ユーザーがいません</p>
		<% end %>
	</div>
</div>

app/views/users/following.html.erb
<div class="row">
	<%= render 'profile', user: @user %>
	<div class="col-sm-9">
		<h2>フォローリスト</h2>
		<% if @users.count > 0 %>
			<%= render 'user_list', user: @user, users: @users %>
		<% else %>
			<p>ユーザーがいません</p>
		<% end %>
	</div>
</div>

app/views/users/quit.html.erb
<div class="offset-sm-4">
	<div class="users__quit">
		<h3>本当に退会しますか？？</h3>
		<p>投稿したものはすべて削除されます。</p>
		<%= link_to "退会しない", user_path(@user), class: "btn btn-primary" %>
		<%= link_to "退会する", user_path, method: :delete, "data-confirm"=> "本当に退会しますか？？", class: "btn btn-danger offset-sm-1" %>
	</div>
</div>

app/views/users/show.html 2.erb
<div class="row">
	<% if signed_in? %>
		<%= render 'profile', user: @user %>
		<div class="col-sm-9">
	<% else %>
		<div class="offset-sm-1 col-sm-10">
	<% end %>
		<h1><%= @user.nickname %>さんのレビュー</h1>
		<% if @reviews.count > 0 %>
			<% @reviews.each do |review| %>
				<%= render 'reviews/post_content', user: @user, review: review %>
			<% end %>
		<% else %>
			<h3 class="review__none">レビューが投稿されてません</h3>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<% if signed_in? %>
		<%= render 'profile', user: @user %>
		<div class="col-sm-9">
	<% else %>
		<div class="offset-sm-1 col-sm-10">
	<% end %>
		<h1><%= @user.nickname %>さんのレビュー</h1>
		<% if @reviews.count > 0 %>
			<% @reviews.each do |review| %>
				<%= render 'reviews/post_content', user: @user, review: review %>
			<% end %>
		<% else %>
			<h3 class="review__none">レビューが投稿されてません</h3>
		<% end %>
	</div>
</div>

app/views/users/timeline.html 2.erb
<div class="row">
	<%= render 'profile', user: @user %>
	<div class="col-sm-9">
		<h1>タイムライン</h1>
		<% if @reviews.count > 0 %>
			<% @reviews.each do |review| %>
				<%= render 'reviews/post_content', user: review.user, review: review %>
			<% end %>
		<% else %>
			<h3 class="review__none">まだレビューがありません</h3>
		<% end %>
	</div>
</div>

app/views/users/timeline.html.erb
<div class="row">
	<%= render 'profile', user: @user %>
	<div class="col-sm-9">
		<h1>タイムライン</h1>
		<% if @reviews.count > 0 %>
			<% @reviews.each do |review| %>
				<%= render 'reviews/post_content', user: review.user, review: review %>
			<% end %>
		<% else %>
			<h3 class="review__none">まだレビューがありません</h3>
		<% end %>
	</div>
</div>