config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#top'
  get 'home/about'
  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :timeline
      get :quit
      get :favorite
    end
    member do
      get :following, :followers
    end
    resources :relationships, only: [:create, :destroy]
  end

  resources :places, only: [:index, :new, :create, :show] do
    collection do
      get :confirm
    end
    resources :reviews, only: [:new, :create, :destroy, :show] do
      # collection do
      #   get :confirm
      # end
      resource :favorites, only: [:create, :destroy]
      resources :review_comments, only: [:create, :destroy]
    end
  end
  get 'favorites/index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @user = current_user
    @q = Place.ransack(params[:q])
    # 遊びジャンルのレビュー
    places_play = Place.where(genre: 1).each do |place_play|
      #Placeのレビューの平均点を取得
      place_play.average = place_play.average_review_rate
    end
    # 平均点が高い順に表示
    @places_play = places_play.sort_by { |place_play| place_play.average || 0 }.reverse

    # 食事ジャンルのレビュー
    places_meal = Place.where(genre: 2).each do |place_meal|
      place_meal.average = place_meal.average_review_rate
    end
    @places_meal = places_meal.sort_by { |place_meal| place_meal.average || 0 }.reverse
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_search_form.html.erb
<%= search_form_for q, url: places_path do |f| %>
	<div class="row">
		<div class="from-group col-sm-3">
			<p>ジャンル</p>
			<div class="form-text">
				<%= f.select :genre_eq, Place.genres.map{|k, v| [Place.genres_i18n[k],v]}, {prompt: "選択してください"}, class: "custom-select" %>
			</div>
		</div>
		<div class="form-group col-sm-3">
			<p>都道府県</p>
			<div class="form-text">
				<%= f.select :prefecture_eq, Place.prefectures.map{|k, v| [Place.prefectures_i18n[k],v]}, {prompt: "選択してください"}, class: "custom-select" %>
			</div>
		</div>
		<div class="form-group col-sm-3">
			<p>キーワード</p>
			<div class="form-text">
				<%= f.text_field :name_cont, class: "form-control" %>
			</div>
		</div>
		<div class="form-group col-sm-1 align-self-end">
			<div class="places__search-action">
				<%= f.submit "検索", class: "btn btn-primary" %>
			</div>
		</div>
	</div>
<% end %>

app/views/home/top.html.erb
<div class="top">
	<div class="top__image">
	</div>
	<h5>ジャンルやキーワードから探す</h5>
	<div class="top__search">
		<%= render 'home/search_form', q: @q %>
	</div>

	<div class="top__play-rank">
		<h5 class="top__genre">遊びランキング</h5>

		<% @places_play.first(3).each.with_index(1) do |place, index| %>
			<div class="top__rank-info">
				<h4><%= index %>位</h4>
				<%= link_to place_path(place) do %>
					<h5><%= place.name %></h5>
					<i> / <%= place.prefecture %></i>
				<% end %>
				<div class="top__rank-rate">
					<!-- レビュー投稿があれば -->
						<% if place.reviews.count > 0 %>
							<%= render 'places/rate_avg', place: place %>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>


	<div class="top__meal-rank">
		<h5 class="top__genre">食事ランキング</h5>
		<% @places_meal.first(3).each.with_index(1) do |place, index| %>
			<div class="top__rank-info">
				<h4><%= index %>位</h4>
				<%= link_to place_path(place) do %>
					<h5><%= place.name %></h5>
					<i> / <%= place.prefecture %></i>
				<% end %>
				<div class="top__rank-rate">
					<!-- レビュー投稿があれば -->
						<% if place.reviews.count > 0 %>
							<%= render 'places/rate_avg', place: place %>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>
<%#= render 'places_rank', place: place, index: index %>