config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#top'
  get 'home/about'
  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :timeline
      get :quit
      get :favorite
    end
    member do
      get :following, :followers
    end
    resources :relationships, only: [:create, :destroy]
  end

  resources :places, only: [:index, :new, :create, :show] do
    collection do
      get :confirm
    end
    resources :reviews, only: [:new, :create, :destroy, :show] do
      # collection do
      #   get :confirm
      # end
      resource :favorites, only: [:create, :destroy]
      resources :review_comments, only: [:create, :destroy]
    end
  end
  get 'favorites/index'
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :reviews, dependent: :destroy

  enum genre: { 遊び: 1, 食事: 2 }
  enum prefecture: {
    北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7, 茨城県: 8, 栃木県: 9, 群馬県: 10,
    埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14, 新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
    岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24, 滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35, 徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39, 福岡県: 40,
    佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46, 沖縄県: 47,
  }

  validates :name, presence: true
  validates :genre, presence: true
  validates :prefecture, presence: true

  attr_accessor :average
  def average_review_rate
    self.reviews.average(:rate)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # before_action :baria_action, only: :confirm
  before_action :require_login, only: [:confirm, :index]
  before_action :check_search_params, only: :confirm
  before_action :authenticate_user!, only: [:new, :confirm]

  def index
    @q = Place.search(search_params)
    @places = @q.result
    # @reviews = []
    # if @places.present?
    #   @places.each do |place|
    #     @reviews.push(place.reviews)
    #   end
    # end
  end

  def new
    @q = Place.ransack(params[:q])
  end

  def create
    @place = Place.new(place_params)
    @place.save
    redirect_to new_place_review_path(place_id: @place.id)
  end

  def show
    @place = Place.find(params[:id])
    @reviews = @place.reviews.reverse_order
  end

  def confirm
    @place = Place.new
    @q = Place.search(search_params)
    @places = @q.result
    # ransackで検索したものを関連付ける
    @place.name = @q.name_eq
    @place.prefecture = @q.prefecture_eq
    @place.genre = @q.genre_eq
  end

  private
  def require_login
    if params[:q].blank?
      redirect_to root_path, notice: "正しいページからをアスセスしてください"
    end
  end
  def search_params
     params.require(:q).permit!
  end

  def place_params
    params.require(:place).permit(:name, :genre, :prefecture)
  end

  # def baria_action
  #   q = Place.ransack(params[:q])
  #   if q.blank?
  #     redirect_to new_place_path, notice: '不正なアクセスです'
  #   end
  # end

  # お店の検索で空白入力を防ぐ
  def check_search_params
    if search_params['name_eq'].blank? ||
      search_params['prefecture_eq'].blank? || search_params['genre_eq'].blank?
      redirect_to new_place_path, notice: '必須項目を記入してください'
    end
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_rate_avg.html.erb
<!-- 平均点数を小数点第一まで -->
<p class="places__avg_rate"><%= place.average_review_rate.round(1) %>点</p>
	<div class="places__star" id="review_star-<%= place.id%>">
	</div>
<!-- jquery 星の表示 -->
<script>
$(document).on('turbolinks:load', function () {
	$('#review_star-<%= place.id %>').raty({
		size: 36,
		starOff:  '<%= asset_path('star-off.png') %>',
		starOn : '<%= asset_path('star-on.png') %>',
		starHalf: '<%= asset_path('star-half.png') %>',
		half: true,
		readOnly: true,
		score: <%= place.reviews.average(:rate).round(1) %>,
	});
});
</script>

app/views/places/confirm.html.erb
<div class="offset-sm-1 col-sm-10">
<% if @places.count == 0%>
	<div class="places__new">
		<h3>該当の場所が無かった為、新規登録します</h3>
		<p>確認してください。</p>
			<div class="places__new-box">
				<div class="places__new-text">
					<p>場所の名前</p>
					<p class="offset-sm-2"><%= @place.name %></p>
				</div>
				<div class="places__new-text">
					<p>都道府県</p>
					<p class="offset-sm-2"><%= @place.prefecture %></p>
				</div>
				<div class="places__new-text">
					<p>ジャンル</p>
					<p class="offset-sm-2"><%= @place.genre %></p>
				</div>

				<%= form_with(model: @place, local: true) do |f| %>
					<%= f.hidden_field :name %>
					<%= f.hidden_field :prefecture, value: @place.prefecture %>
					<%= f.hidden_field :genre, value: @place.genre %>
					<div class="offset-sm-2">
						<%= f.submit "新規登録する", class: "btn btn-primary" %>
					</div>
				<% end %>
			</div>
		</div>
	</div>

<% else %>
	<div class="places">
		<h2>もしかしてこちらと同じですか？？</h2>
	 	<table class="places__list">
	 		<thead>
	 			<tr>
	 				<th>名前</th>
	 				<th>ジャンル</th>
	 				<th>都道府県</th>
	 				<th></th>
	 			</tr>
	 		</thead>
	 		<% @places.each do |place| %>
	 		<tbody>
	 			<tr>
	 				<td><%= link_to place_path(place) do %>
	 						<%= place.name %>
	 					<% end %>
	 				</td>
	 				<td><%= place.genre %></td>
	 				<td><%= place.prefecture %></td>
	 				<td><%= link_to "ここと同じ場所です", new_place_review_path(place.id), class: "btn btn-yellow" %></td>
	 			</tr>
	 		</tbody>
	 		<% end %>
	 	</table>
		<%= form_with(model: @place, local: true) do |f| %>
			<%= f.hidden_field :name %>
			<%= f.hidden_field :prefecture, value: @place.prefecture %>
			<%= f.hidden_field :genre, value: @place.genre %>
			<div class="places__new-link">
				<%= f.submit "当てはまらないので、新規登録します。", class: "btn btn-primary" %>
			</div>
		<% end %>
	 </div>
<% end %>
</div>

app/views/places/index.html.erb
<%= render 'home/search_form', q: @q %>

<h2>検索結果</h2>
<% if @places.blank? %>
	<h3>検索に一致するものはありませんでした。</h3>
<% else %>
	<div class="places">
	 	<table class="places__list">
	 		<thead>
	 			<tr>
	 				<th>名前</th>
	 				<th>評価</th>
	 				<th>ジャンル</th>
	 				<th>都道府県</th>
	 			</tr>
	 		</thead>
	 		<% @places.each do |place| %>
	 		<tbody>
	 			<tr>
	 				<td><%= link_to place_path(place) do %>
	 						<%= place.name %>
	 					<% end %>
	 				</td>
	 				<!-- レビュー投稿があれば -->
	 				<% if place.reviews.count > 0 %>
	 				 <td><%= render 'rate_avg', place: place %></td>
	 				<% else %>
	 					<td>レビューなし</td>
	 				<% end %>
	 				<td><%= place.genre %></td>
	 				<td><%= place.prefecture %></td>
	 			</tr>
	 		</tbody>
	 		<% end %>
	 	</table>
	</div>
<% end %>

app/views/places/new.html.erb
<div class="places offset-sm-1">
<h2>レビュー投稿</h2>
<P>既に登録されてる場所かお調べします。</P>
	<div class="places__form">
		<%= search_form_for @q, url: confirm_places_path do |f| %>
			<div class="form-group row">
				<div class="col-sm-2">
					<div class="form-title">
						<%= f.label :name, "場所の名前", class: "col-form-label" %>
						<span class="form-red">必須</span>
					</div>
				</div>
				<div class="col-sm-5">
					<%= f.text_field :name_eq, autofocus: true, class: "form-control" %>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-sm-2">
					<%= f.label :prefecture, "都道府県　" %>
					<span class="form-red">必須</span>
				</div>
				<div class="col-sm-3">
					<%= f.select :prefecture_eq, Place.prefectures.map{|k, v| [Place.prefectures_i18n[k],v]},{prompt:"選択してください"}, class: "custom-select" %>
				</div>
			</div>

			<div class="form-group row">
				<div class="col-sm-2">
					<label>ジャンル　</label>
					<span class="form-red">必須</span>
				</div>
				<div class="form-check">
					<%= f.radio_button :genre_eq, "1" %>
					<%= f.label :genre_eq, "遊び",'', value:"1", class: "form-check-label" %>
				</div>
				<div class="form-check">
					<%= f.radio_button :genre_eq, "2" %>
					<%= f.label :genre_eq, "食事", value: "2", class: "form-check-label" %>
				</div>
			</div>

			<div class="form-group row">
			    <div class="offset-sm-2 col-sm-10">
			      <%= f.submit "検索", class: "btn btn-primary" %>
			    </div>
			  </div>
		<% end %>
	</div>
</div>

app/views/places/show.html.erb
<div class="places">
	<div class="row">
			<h1><%= @place.name %></h1>
			<div class="places__review-link">
				<%= link_to "ここのレビューをする", new_place_review_path(@place.id), class: "btn btn-warning" %>
			</div>
	</div>

	<% if @reviews.count > 0 %>
		<div class="places__rate row">
			<%= render 'places/rate_avg', place: @place %>
		</div>
	<% end %>

	<div class="places__info row">
		<i><%= @place.genre %></i>
		<i>　/　<%= @place.prefecture %>　/　</i>
		<i>レビュー<%= @reviews.count %>件</i>
	</div>
	<h3>レビュー 一覧</h3>

	<% if @reviews.count > 0 %>
		<% @reviews.each do |review| %>
			<%= render 'reviews/post_content', review: review, user: review.user, age: @age%>
		<% end %>
	<% else %>
		<h3 class="review__none">レビューが投稿されてません</h3>
	<% end %>
</div>